---
application:
  name: "coinhub"
  project: "coinhub"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "coinhub-db"
  version: "8.0"
routers:
- name: "main-coinhub"
  routes:
  - application_name: "coinhub"
    paths:
    - "/*"
