import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import axios from "axios";
import Env from "@ioc:Adonis/Core/Env";
import Recipe from "App/Models/Recipe";
import {fdaRequiredNutrients} from "App/Services/Diethunter/Helpers/fdaRequiredNutrients";
import User from "App/Models/User";
import Comment from "App/Models/Comment";

export default class RecipeSeeder extends BaseSeeder {
	public async run() {
		let numberOfRecipes = 101
		for(let i = 1;i<numberOfRecipes+1;i++) {
			let recipe = await axios.get(`https://api.spoonacular.com/recipes/${i}/information?apiKey=${Env.get(
				'SPOONACULAR_API_KEY'
			)}&includeNutrition=true`)

			let created = await Recipe.create({
				title: recipe.data.title,
				rawTitle: recipe.data.title.toLowerCase(),
				ingredients: JSON.stringify(recipe.data.nutrition.ingredients.map(ingredient => {
					return {amount: ingredient.amount + " " + ingredient.unit, ingredient: ingredient.name}
				})),
				instructions: JSON.stringify(recipe.data.instructions.slice(3, -4).split(".")),
				nutrition: JSON.stringify(
					recipe.data.nutrition.nutrients.filter((nutrient) =>
						fdaRequiredNutrients.includes(nutrient.name)
					)
				),
				description: "Autogenerated recipe by Diethunter",
				halal: false,
				kosher: false,
				vegan: recipe.data.vegan,
				vegetarian: recipe.data.vegetarian,
				nutfree: false,
				userId: (await User.findBy('username', 'Diethunter101'))!.id,
				cuisine: recipe.data.cuisines[0] || 'American',
				rating: 5
			})
			await Comment.create({
				recipeId: created.id,
				userId: (await User.findBy('username', 'Diethunter101'))!.id,
				text: "Verified recipe",
				rating: 5
			})
		}
	}
}
